Handle wallet path which points directly to a PEM file.
lovetodream/oracle-nio pull request #38
Opened 2024-06-20 21:42 UTC by huyphams

Do you think we should handle the case where the user points wallet directly to PEM file and not folder?

2024-06-20 22:27 UTC, cjbj commented
Purely for consistency with other Oracle drivers, you may not want this.  But I can understand the desire for it

2024-06-20 23:25 UTC, huyphams commented
So will you merge this PR? I think it is helpful.

2024-06-21 08:26 UTC, lovetodream commented
While I do agree that this is a good addition in general, I don't think we should implement it as part of the current method. 
The wallet is a specific term in Oracle, it's a container for credentials (as I understand it). 

> Purely for consistency with other Oracle drivers, you may not want this. But I can understand the desire for it

That's my interpretation of why other drivers don't have this, or is there something else we should know about @cjbj?

I'd like to propose adding an overload e.g. `makeOracleWalletConfiguration(pemFile: String, pemPassword: String)` to clearly distinguish between wallet and standalone PEM file. Even if the end result is the same. 

This also avoids the use of Foundation, which I'd generally like to avoid, as it might cause headaches on non-Apple platforms in its current form. Library users can still implement such a check themselves and use the appropriate method if they require such functionality.

What do you think @huyphams?

BTW I'm a big fan and active user of TablePlus, keep up the great work :)

2024-06-21 08:27 UTC, lovetodream requested changes

2024-06-21 08:27 UTC, lovetodream commented on Sources/OracleNIO/TLSConfiguration+Oracle.swift
> +import Foundation
We'd like to avoid use of FileManager

2024-06-21 08:27 UTC, lovetodream commented on Sources/OracleNIO/TLSConfiguration+Oracle.swift
> +            file = wallet
Let's move this to a dedicated method, see PR comment for context

2024-06-21 19:46 UTC, huyphams commented
Make sense @lovetodream I just updated the PR.

> BTW I'm a big fan and active user of TablePlus, keep up the great work :)

I'm glad that you like it 😄

2024-06-24 16:59 UTC, lovetodream approved these changes

2024-06-24 17:13 UTC, merged